version: "3.9"

services:
  yt_postgres:
    image: postgres:15.3-alpine
    container_name: yt_postgres
    volumes:
      - ~/.pg/pg_data/yt:/var/lib/postgresql/data
    env_file:
      - .env

  youtube_project:
    image: djproject:latest
    container_name: yt_django
    depends_on:
      - yt_postgres
    volumes:
      - ./static_root:/yt/static
      - ./media:/yt/media

    command: >
      bash -c "python manage.py collectstatic --noinput && python manage.py migrate  && gunicorn -b 0.0.0.0:8000 myproject.wsgi:application"
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: yt_nginx
    image: yt_nginx
    volumes:
      - ./static_root:/yt/static
      - ./media:/yt/media
    depends_on:
      - youtube_project
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"

volumes:
  static_volume:
  media_volume:

